CC=gcc
CFLAGS=-I. -Iglad/include
LDFLAGS=-lGL -lSDL3 -fPIC -shared -O3
SOURCES=cpunes.c instr.c linux/platform.c palette.c sdl3_opengl3.c debugger.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=libnes.so
LIB_DIR=/usr/local/lib64

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

.c.o:
	@echo [CC] $<
	@cc -c $< $(CFLAGS) $(LDFLAGS) -o $@

clean:
	rm -f *o
	rm -f linux/*.o
	rm -f $(EXECUTABLE)
