CC=gcc
CFLAGS=-I. -Iglad/include
LDFLAGS=-lGL -lSDL3
SOURCES=cpunes.c handlers.c sdl3_opengl4.c palette.c app_opengl4.c linux/platform.c glad/src/gl.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=app
LIB_DIR=/usr/local/lib64

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

.c.o:
	@echo [CC] $<
	@cc -c $< $(CFLAGS) $(LDFLAGS) -o $@

clean:
	rm -f *.o
	rm -f $(EXECUTABLE)
