CC=gcc
CFLAGS=-I.
LDFLAGS=-lGLESv2 -lSDL3 -g
SOURCES=cpunes.c handlers.c sdl3_opengl3.c palette.c app.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=app
LIB_DIR=/usr/local/lib64

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

.c.o:
	@echo [CC] $<
	@cc -c $< $(CFLAGS) $(LDFLAGS) -o $@

clean:
	rm -f *o
	rm -f $(EXECUTABLE)
